// Options: https://prettier.io/docs/en/options.html
module.exports = {
    tabWidth: 4,
    useTabs: false,
    trailingComma: 'es5',
    semi: false,
    singleQuote: true,
    endOfLine: 'lf',
    bracketSpacing: true,
    arrowParens: 'avoid',
    printWidth: 80,
    htmlWhitespaceSensitivity: 'css',
    // parser: 'babel',
    proseWrap: 'preserve',
    jsxBracketSameLine: false,
    jsxSingleQuote: false,
    quoteProps: 'as-needed',
    twigMelodyPlugins: ['node_modules/prettier-plugin-twig-enhancements'],
    plugins: ['./node_modules/prettier-plugin-twig-melody'],
}
